version: '3'

services:
  backend:
    build:
      dockerfile: docker/backend/Dockerfile
      context: .
    volumes:
      - ./backend:/app
    ports:
    - 9900:8000
    env_file:
      - .env
    links:
      - db
    command: ["python", "-m", "run_server"]

  db:
    image: postgres:12
    ports:
    - 5432:5432
    env_file:
      - .env
